### ISSUE TITLE
RpiBoard3B doesn't implement beDigitalOutput

### ISSUE THREAD

**Issue by capsulecorplab** [SquareBracketAssociates/Booklet-APharoThingsTutorial#20]
**UsingPharoThingsTools** chapter references calling `beDigitalOutput` on an `RpiBoard3B` object in [L86](https://github.com/SquareBracketAssociates/Booklet-APharoThingsTutorial/blob/master/Chapters/Chap06-UsingPharoThingsTools/Chap06-UsingPharoThingsTools.pillar#L86), but it isn't implemented.

An alternative solution, for the sake of a working example, could use an instance of `PotGPIO`:
```
led := PotGPIO id: 4.
led board: RpiBoard3B current; beDigitalOutput
```

**Comment by oliveiraallex** [comment]
Fixed
https://github.com/SquareBracketAssociates/Booklet-APharoThingsTutorial/pull/21
